include:
  - board: seeed_xiao_ble
    shield: KeyballBLE_R
    cmake-args: -DCONFIG_ZMK_STUDIO=n
  - board: seeed_xiao_ble
    shield: KeyballBLE_L
    cmake-args: -DCONFIG_ZMK_STUDIO=n
  - board: seeed_xiao_ble
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_STUDIO=n
